import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-500 text-black font-bold text-2xl p-4 flex justify-between items-center">
          <div>Blogs Posts</div>

          <ul className="flex space-x-4">
            <li>
              <Link href="/todos" className="hover:underline px-4">
                Todos
              </Link>
            </li>
            <li>
              <Link href="/posts" className="hover:underline px-4">
                Posts
              </Link>
            </li>
            <li>
              <Link href="/users" className="hover:underline px-4">
                Users
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
